{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cb-pdp.fullname" . }}
  {{- with .Values.serviceMonitor.namespace }}
  namespace: {{ . | quote }}
  {{- end }}
  labels:
    {{- include "cb-pdp.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels: {{- include "cb-pdp.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.metricsPath | default "/metrics" }}
      interval: {{ .Values.serviceMonitor.interval | default "30s" }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout | default "10s" }}
      {{- with .Values.serviceMonitor.relabelings }}
      relabelings: {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
