// AUTO-GENERATED by packages/schema-packs/scripts/generate-action-schemas.mts.
// DO NOT EDIT BY HAND. Regenerate with: pnpm -F @auto-nomos/schema-packs gen:schemas
// Source of truth: packages/adapters/spec/<pack>.yaml
//
// This file is the apiCall floor for the PDP proxy. Hand-curated overrides
// in <pack>/schemas.ts can tighten body shape further. See types.ts
// `mergeActionSchemas` for how the two layers combine.
// pack=discord actions=22 mapped=22

import { z } from 'zod';
import type { ActionSchemas } from '../types.js';

const safePath = z
  .string()
  .min(1)
  .refine((p: string) => !p.includes('..') && !p.includes('//'), {
    message: 'apiCall.path must not contain ".." or "//" segments',
  });

export const generated: Partial<Record<string, ActionSchemas>> = {
  '/discord/guild/read': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/guilds\/.+$/.test(p),
        'apiCall.path does not match action template /guilds/{guild_id}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/discord/guild/members': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/guilds\/[^/]+\/members$/.test(p),
        'apiCall.path does not match action template /guilds/{guild_id}/members',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/discord/guild/modify': {
    apiCallSchema: z.object({
      method: z.literal('PATCH'),
      path: safePath.refine(
        (p) => /^\/guilds\/.+$/.test(p),
        'apiCall.path does not match action template /guilds/{guild_id}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/discord/channel/list': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/guilds\/[^/]+\/channels$/.test(p),
        'apiCall.path does not match action template /guilds/{guild_id}/channels',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/discord/channel/read': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/channels\/.+$/.test(p),
        'apiCall.path does not match action template /channels/{channel_id}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/discord/channel/create': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/guilds\/[^/]+\/channels$/.test(p),
        'apiCall.path does not match action template /guilds/{guild_id}/channels',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          name: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/discord/channel/modify': {
    apiCallSchema: z.object({
      method: z.literal('PATCH'),
      path: safePath.refine(
        (p) => /^\/channels\/.+$/.test(p),
        'apiCall.path does not match action template /channels/{channel_id}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/discord/channel/delete': {
    apiCallSchema: z.object({
      method: z.literal('DELETE'),
      path: safePath.refine(
        (p) => /^\/channels\/.+$/.test(p),
        'apiCall.path does not match action template /channels/{channel_id}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/discord/channel/permissions': {
    apiCallSchema: z.object({
      method: z.literal('PUT'),
      path: safePath.refine(
        (p) => /^\/channels\/[^/]+\/permissions\/.+$/.test(p),
        'apiCall.path does not match action template /channels/{channel_id}/permissions/{overwrite_id}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          type: z.number().int(),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/discord/message/list': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/channels\/[^/]+\/messages$/.test(p),
        'apiCall.path does not match action template /channels/{channel_id}/messages',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/discord/message/post': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/channels\/[^/]+\/messages$/.test(p),
        'apiCall.path does not match action template /channels/{channel_id}/messages',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/discord/message/edit': {
    apiCallSchema: z.object({
      method: z.literal('PATCH'),
      path: safePath.refine(
        (p) => /^\/channels\/[^/]+\/messages\/.+$/.test(p),
        'apiCall.path does not match action template /channels/{channel_id}/messages/{message_id}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/discord/message/delete': {
    apiCallSchema: z.object({
      method: z.literal('DELETE'),
      path: safePath.refine(
        (p) => /^\/channels\/[^/]+\/messages\/.+$/.test(p),
        'apiCall.path does not match action template /channels/{channel_id}/messages/{message_id}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/discord/role/list': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/guilds\/[^/]+\/roles$/.test(p),
        'apiCall.path does not match action template /guilds/{guild_id}/roles',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/discord/role/create': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/guilds\/[^/]+\/roles$/.test(p),
        'apiCall.path does not match action template /guilds/{guild_id}/roles',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          name: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/discord/role/modify': {
    apiCallSchema: z.object({
      method: z.literal('PATCH'),
      path: safePath.refine(
        (p) => /^\/guilds\/[^/]+\/roles\/.+$/.test(p),
        'apiCall.path does not match action template /guilds/{guild_id}/roles/{role_id}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/discord/role/delete': {
    apiCallSchema: z.object({
      method: z.literal('DELETE'),
      path: safePath.refine(
        (p) => /^\/guilds\/[^/]+\/roles\/.+$/.test(p),
        'apiCall.path does not match action template /guilds/{guild_id}/roles/{role_id}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/discord/member/add_role': {
    apiCallSchema: z.object({
      method: z.literal('PUT'),
      path: safePath.refine(
        (p) => /^\/guilds\/[^/]+\/members\/[^/]+\/roles\/.+$/.test(p),
        'apiCall.path does not match action template /guilds/{guild_id}/members/{user_id}/roles/{role_id}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/discord/member/remove_role': {
    apiCallSchema: z.object({
      method: z.literal('DELETE'),
      path: safePath.refine(
        (p) => /^\/guilds\/[^/]+\/members\/[^/]+\/roles\/.+$/.test(p),
        'apiCall.path does not match action template /guilds/{guild_id}/members/{user_id}/roles/{role_id}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/discord/invite/create': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/channels\/[^/]+\/invites$/.test(p),
        'apiCall.path does not match action template /channels/{channel_id}/invites',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/discord/webhook/create': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/channels\/[^/]+\/webhooks$/.test(p),
        'apiCall.path does not match action template /channels/{channel_id}/webhooks',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          name: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/discord/emoji/list': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/guilds\/[^/]+\/emojis$/.test(p),
        'apiCall.path does not match action template /guilds/{guild_id}/emojis',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
};
