// AUTO-GENERATED by packages/schema-packs/scripts/generate-action-schemas.mts.
// DO NOT EDIT BY HAND. Regenerate with: pnpm -F @auto-nomos/schema-packs gen:schemas
// Source of truth: packages/adapters/spec/<pack>.yaml
//
// This file is the apiCall floor for the PDP proxy. Hand-curated overrides
// in <pack>/schemas.ts can tighten body shape further. See types.ts
// `mergeActionSchemas` for how the two layers combine.
// pack=filesystem actions=11 mapped=11

import { z } from 'zod';
import type { ActionSchemas } from '../types.js';

const safePath = z
  .string()
  .min(1)
  .refine((p: string) => !p.includes('..') && !p.includes('//'), {
    message: 'apiCall.path must not contain ".." or "//" segments',
  });

export const generated: Partial<Record<string, ActionSchemas>> = {
  '/filesystem/file/read': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/file\/read$/.test(p),
        'apiCall.path does not match action template /file/read',
      ),
      query: z
        .object({
          path: z.string(),
        })
        .catchall(z.string())
        .optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/filesystem/file/write': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/file\/write$/.test(p),
        'apiCall.path does not match action template /file/write',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          path: z.string().min(1),
          content: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/filesystem/file/create': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/file\/create$/.test(p),
        'apiCall.path does not match action template /file/create',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          path: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/filesystem/file/delete': {
    apiCallSchema: z.object({
      method: z.literal('DELETE'),
      path: safePath.refine(
        (p) => /^\/file\/delete$/.test(p),
        'apiCall.path does not match action template /file/delete',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          path: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/filesystem/file/move': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/file\/move$/.test(p),
        'apiCall.path does not match action template /file/move',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          path: z.string().min(1),
          destination: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/filesystem/file/copy': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/file\/copy$/.test(p),
        'apiCall.path does not match action template /file/copy',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          path: z.string().min(1),
          destination: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/filesystem/dir/list': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/dir\/list$/.test(p),
        'apiCall.path does not match action template /dir/list',
      ),
      query: z
        .object({
          path: z.string(),
        })
        .catchall(z.string())
        .optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/filesystem/dir/tree': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/dir\/tree$/.test(p),
        'apiCall.path does not match action template /dir/tree',
      ),
      query: z
        .object({
          path: z.string(),
        })
        .catchall(z.string())
        .optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/filesystem/dir/create': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/dir\/create$/.test(p),
        'apiCall.path does not match action template /dir/create',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          path: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/filesystem/dir/delete': {
    apiCallSchema: z.object({
      method: z.literal('DELETE'),
      path: safePath.refine(
        (p) => /^\/dir\/delete$/.test(p),
        'apiCall.path does not match action template /dir/delete',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          path: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/filesystem/dir/delete_recursive': {
    apiCallSchema: z.object({
      method: z.literal('DELETE'),
      path: safePath.refine(
        (p) => /^\/dir\/delete_recursive$/.test(p),
        'apiCall.path does not match action template /dir/delete_recursive',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          path: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
};
