// AUTO-GENERATED by packages/schema-packs/scripts/generate-action-schemas.mts.
// DO NOT EDIT BY HAND. Regenerate with: pnpm -F @auto-nomos/schema-packs gen:schemas
// Source of truth: packages/adapters/spec/<pack>.yaml
//
// This file is the apiCall floor for the PDP proxy. Hand-curated overrides
// in <pack>/schemas.ts can tighten body shape further. See types.ts
// `mergeActionSchemas` for how the two layers combine.
// pack=github actions=29 mapped=29

import { z } from 'zod';
import type { ActionSchemas } from '../types.js';

const safePath = z
  .string()
  .min(1)
  .refine((p: string) => !p.includes('..') && !p.includes('//'), {
    message: 'apiCall.path must not contain ".." or "//" segments',
  });

export const generated: Partial<Record<string, ActionSchemas>> = {
  '/github/issue/list': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/repos\/[^/]+\/[^/]+\/issues$/.test(p),
        'apiCall.path does not match action template /repos/{owner}/{repo}/issues',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/github/issue/read': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/repos\/[^/]+\/[^/]+\/issues\/.+$/.test(p),
        'apiCall.path does not match action template /repos/{owner}/{repo}/issues/{issue_number}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/github/repo/create': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/user\/repos$/.test(p),
        'apiCall.path does not match action template /user/repos',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          name: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/github/issue/create': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/repos\/[^/]+\/[^/]+\/issues$/.test(p),
        'apiCall.path does not match action template /repos/{owner}/{repo}/issues',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          title: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/github/issue/comment': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/repos\/[^/]+\/[^/]+\/issues\/[^/]+\/comments$/.test(p),
        'apiCall.path does not match action template /repos/{owner}/{repo}/issues/{issue_number}/comments',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          body: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/github/repo/list': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/user\/repos$/.test(p),
        'apiCall.path does not match action template /user/repos',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/github/user/read': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/user$/.test(p),
        'apiCall.path does not match action template /user',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/github/issue/close': {
    apiCallSchema: z.object({
      method: z.literal('PATCH'),
      path: safePath.refine(
        (p) => /^\/repos\/[^/]+\/[^/]+\/issues\/.+$/.test(p),
        'apiCall.path does not match action template /repos/{owner}/{repo}/issues/{issue_number}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          state: z.enum(['closed']),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/github/repo/delete': {
    apiCallSchema: z.object({
      method: z.literal('DELETE'),
      path: safePath.refine(
        (p) => /^\/repos\/[^/]+\/.+$/.test(p),
        'apiCall.path does not match action template /repos/{owner}/{repo}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/github/repo/read': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/repos\/[^/]+\/.+$/.test(p),
        'apiCall.path does not match action template /repos/{owner}/{repo}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/github/branch/list': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/repos\/[^/]+\/[^/]+\/branches$/.test(p),
        'apiCall.path does not match action template /repos/{owner}/{repo}/branches',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/github/content/read': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/repos\/[^/]+\/[^/]+\/contents\/.+$/.test(p),
        'apiCall.path does not match action template /repos/{owner}/{repo}/contents/{path}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/github/pr/list': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/repos\/[^/]+\/[^/]+\/pulls$/.test(p),
        'apiCall.path does not match action template /repos/{owner}/{repo}/pulls',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/github/pr/read': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/repos\/[^/]+\/[^/]+\/pulls\/.+$/.test(p),
        'apiCall.path does not match action template /repos/{owner}/{repo}/pulls/{pull_number}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/github/pr/create': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/repos\/[^/]+\/[^/]+\/pulls$/.test(p),
        'apiCall.path does not match action template /repos/{owner}/{repo}/pulls',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          title: z.string().min(1),
          head: z.string().min(1),
          base: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/github/pr/merge': {
    apiCallSchema: z.object({
      method: z.literal('PUT'),
      path: safePath.refine(
        (p) => /^\/repos\/[^/]+\/[^/]+\/pulls\/[^/]+\/merge$/.test(p),
        'apiCall.path does not match action template /repos/{owner}/{repo}/pulls/{pull_number}/merge',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/github/branch/create': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/repos\/[^/]+\/[^/]+\/git\/refs$/.test(p),
        'apiCall.path does not match action template /repos/{owner}/{repo}/git/refs',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          ref: z.string().min(1),
          sha: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/github/content/update': {
    apiCallSchema: z.object({
      method: z.literal('PUT'),
      path: safePath.refine(
        (p) => /^\/repos\/[^/]+\/[^/]+\/contents\/.+$/.test(p),
        'apiCall.path does not match action template /repos/{owner}/{repo}/contents/{path}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          message: z.string().min(1),
          content: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/github/commit/list': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/repos\/[^/]+\/[^/]+\/commits$/.test(p),
        'apiCall.path does not match action template /repos/{owner}/{repo}/commits',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/github/issue/search': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/search\/issues$/.test(p),
        'apiCall.path does not match action template /search/issues',
      ),
      query: z
        .object({
          q: z.string(),
        })
        .catchall(z.string())
        .optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/github/repo/search': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/search\/repositories$/.test(p),
        'apiCall.path does not match action template /search/repositories',
      ),
      query: z
        .object({
          q: z.string(),
        })
        .catchall(z.string())
        .optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/github/label/list': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/repos\/[^/]+\/[^/]+\/labels$/.test(p),
        'apiCall.path does not match action template /repos/{owner}/{repo}/labels',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/github/issue/label': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/repos\/[^/]+\/[^/]+\/issues\/[^/]+\/labels$/.test(p),
        'apiCall.path does not match action template /repos/{owner}/{repo}/issues/{issue_number}/labels',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          labels: z.array(z.unknown()),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/github/issue/comment/list': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/repos\/[^/]+\/[^/]+\/issues\/[^/]+\/comments$/.test(p),
        'apiCall.path does not match action template /repos/{owner}/{repo}/issues/{issue_number}/comments',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/github/release/create': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/repos\/[^/]+\/[^/]+\/releases$/.test(p),
        'apiCall.path does not match action template /repos/{owner}/{repo}/releases',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          tag_name: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/github/workflow/run/list': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/repos\/[^/]+\/[^/]+\/actions\/runs$/.test(p),
        'apiCall.path does not match action template /repos/{owner}/{repo}/actions/runs',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/github/workflow/trigger': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/repos\/[^/]+\/[^/]+\/actions\/workflows\/[^/]+\/dispatches$/.test(p),
        'apiCall.path does not match action template /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          ref: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/github/pr/review/list': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/repos\/[^/]+\/[^/]+\/pulls\/[^/]+\/reviews$/.test(p),
        'apiCall.path does not match action template /repos/{owner}/{repo}/pulls/{pull_number}/reviews',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/github/pr/review/submit': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/repos\/[^/]+\/[^/]+\/pulls\/[^/]+\/reviews$/.test(p),
        'apiCall.path does not match action template /repos/{owner}/{repo}/pulls/{pull_number}/reviews',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          event: z.enum(['APPROVE', 'REQUEST_CHANGES', 'COMMENT']),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
};
