// AUTO-GENERATED by packages/schema-packs/scripts/generate-action-schemas.mts.
// DO NOT EDIT BY HAND. Regenerate with: pnpm -F @auto-nomos/schema-packs gen:schemas
// Source of truth: packages/adapters/spec/<pack>.yaml
//
// This file is the apiCall floor for the PDP proxy. Hand-curated overrides
// in <pack>/schemas.ts can tighten body shape further. See types.ts
// `mergeActionSchemas` for how the two layers combine.
// pack=google_sheets actions=6 mapped=6

import { z } from 'zod';
import type { ActionSchemas } from '../types.js';

const safePath = z
  .string()
  .min(1)
  .refine((p: string) => !p.includes('..') && !p.includes('//'), {
    message: 'apiCall.path must not contain ".." or "//" segments',
  });

export const generated: Partial<Record<string, ActionSchemas>> = {
  '/google/sheets/spreadsheet/create': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/spreadsheets$/.test(p),
        'apiCall.path does not match action template /spreadsheets',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          properties: z.record(z.string(), z.unknown()),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/sheets/spreadsheet/read': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/spreadsheets\/.+$/.test(p),
        'apiCall.path does not match action template /spreadsheets/{spreadsheetId}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/sheets/values/read': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/spreadsheets\/[^/]+\/values\/.+$/.test(p),
        'apiCall.path does not match action template /spreadsheets/{spreadsheetId}/values/{range}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/sheets/values/update': {
    apiCallSchema: z.object({
      method: z.literal('PUT'),
      path: safePath.refine(
        (p) => /^\/spreadsheets\/[^/]+\/values\/.+$/.test(p),
        'apiCall.path does not match action template /spreadsheets/{spreadsheetId}/values/{range}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          values: z.array(z.unknown()),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/sheets/values/append': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/spreadsheets\/[^/]+\/values\/[^/]+:append$/.test(p),
        'apiCall.path does not match action template /spreadsheets/{spreadsheetId}/values/{range}:append',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          values: z.array(z.unknown()),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/sheets/spreadsheet/batch_update': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/spreadsheets\/[^/]+:batchUpdate$/.test(p),
        'apiCall.path does not match action template /spreadsheets/{spreadsheetId}:batchUpdate',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          requests: z.array(z.unknown()),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
};
