// AUTO-GENERATED by packages/schema-packs/scripts/generate-action-schemas.mts.
// DO NOT EDIT BY HAND. Regenerate with: pnpm -F @auto-nomos/schema-packs gen:schemas
// Source of truth: packages/adapters/spec/<pack>.yaml
//
// This file is the apiCall floor for the PDP proxy. Hand-curated overrides
// in <pack>/schemas.ts can tighten body shape further. See types.ts
// `mergeActionSchemas` for how the two layers combine.
// pack=google_docs actions=11 mapped=11

import { z } from 'zod';
import type { ActionSchemas } from '../types.js';

const safePath = z
  .string()
  .min(1)
  .refine((p: string) => !p.includes('..') && !p.includes('//'), {
    message: 'apiCall.path must not contain ".." or "//" segments',
  });

export const generated: Partial<Record<string, ActionSchemas>> = {
  '/google/docs/document/create': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/documents$/.test(p),
        'apiCall.path does not match action template /documents',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          title: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/docs/document/read': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/documents\/.+$/.test(p),
        'apiCall.path does not match action template /documents/{documentId}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/docs/document/batch_update': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/documents\/[^/]+:batchUpdate$/.test(p),
        'apiCall.path does not match action template /documents/{documentId}:batchUpdate',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          requests: z.array(z.unknown()),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/docs/document/replace_text': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/documents\/[^/]+:batchUpdate$/.test(p),
        'apiCall.path does not match action template /documents/{documentId}:batchUpdate',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          text: z.string().min(1),
          replaceText: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/docs/document/insert_text': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/documents\/[^/]+:batchUpdate$/.test(p),
        'apiCall.path does not match action template /documents/{documentId}:batchUpdate',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          requests: z.array(z.unknown()),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/docs/document/delete_text': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/documents\/[^/]+:batchUpdate$/.test(p),
        'apiCall.path does not match action template /documents/{documentId}:batchUpdate',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          requests: z.array(z.unknown()),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/docs/document/format_text': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/documents\/[^/]+:batchUpdate$/.test(p),
        'apiCall.path does not match action template /documents/{documentId}:batchUpdate',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          requests: z.array(z.unknown()),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/docs/document/insert_table': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/documents\/[^/]+:batchUpdate$/.test(p),
        'apiCall.path does not match action template /documents/{documentId}:batchUpdate',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          requests: z.array(z.unknown()),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/docs/document/insert_image': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/documents\/[^/]+:batchUpdate$/.test(p),
        'apiCall.path does not match action template /documents/{documentId}:batchUpdate',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          requests: z.array(z.unknown()),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/docs/document/named_range/create': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/documents\/[^/]+:batchUpdate$/.test(p),
        'apiCall.path does not match action template /documents/{documentId}:batchUpdate',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          requests: z.array(z.unknown()),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/docs/document/revisions/read': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/documents\/.+$/.test(p),
        'apiCall.path does not match action template /documents/{documentId}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
};
