// AUTO-GENERATED by packages/schema-packs/scripts/generate-action-schemas.mts.
// DO NOT EDIT BY HAND. Regenerate with: pnpm -F @auto-nomos/schema-packs gen:schemas
// Source of truth: packages/adapters/spec/<pack>.yaml
//
// This file is the apiCall floor for the PDP proxy. Hand-curated overrides
// in <pack>/schemas.ts can tighten body shape further. See types.ts
// `mergeActionSchemas` for how the two layers combine.
// pack=google_tasks actions=6 mapped=6

import { z } from 'zod';
import type { ActionSchemas } from '../types.js';

const safePath = z
  .string()
  .min(1)
  .refine((p: string) => !p.includes('..') && !p.includes('//'), {
    message: 'apiCall.path must not contain ".." or "//" segments',
  });

export const generated: Partial<Record<string, ActionSchemas>> = {
  '/google/tasks/tasklist/list': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/users\/@me\/lists$/.test(p),
        'apiCall.path does not match action template /users/@me/lists',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/tasks/task/list': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/lists\/[^/]+\/tasks$/.test(p),
        'apiCall.path does not match action template /lists/{tasklist}/tasks',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/tasks/task/read': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/lists\/[^/]+\/tasks\/.+$/.test(p),
        'apiCall.path does not match action template /lists/{tasklist}/tasks/{task}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/tasks/task/create': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/lists\/[^/]+\/tasks$/.test(p),
        'apiCall.path does not match action template /lists/{tasklist}/tasks',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          title: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/tasks/task/update': {
    apiCallSchema: z.object({
      method: z.literal('PATCH'),
      path: safePath.refine(
        (p) => /^\/lists\/[^/]+\/tasks\/.+$/.test(p),
        'apiCall.path does not match action template /lists/{tasklist}/tasks/{task}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/tasks/task/delete': {
    apiCallSchema: z.object({
      method: z.literal('DELETE'),
      path: safePath.refine(
        (p) => /^\/lists\/[^/]+\/tasks\/.+$/.test(p),
        'apiCall.path does not match action template /lists/{tasklist}/tasks/{task}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
};
