// AUTO-GENERATED by packages/schema-packs/scripts/generate-action-schemas.mts.
// DO NOT EDIT BY HAND. Regenerate with: pnpm -F @auto-nomos/schema-packs gen:schemas
// Source of truth: packages/adapters/spec/<pack>.yaml
//
// This file is the apiCall floor for the PDP proxy. Hand-curated overrides
// in <pack>/schemas.ts can tighten body shape further. See types.ts
// `mergeActionSchemas` for how the two layers combine.
// pack=google actions=20 mapped=20

import { z } from 'zod';
import type { ActionSchemas } from '../types.js';

const safePath = z
  .string()
  .min(1)
  .refine((p: string) => !p.includes('..') && !p.includes('//'), {
    message: 'apiCall.path must not contain ".." or "//" segments',
  });

export const generated: Partial<Record<string, ActionSchemas>> = {
  '/google/drive/list': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/files$/.test(p),
        'apiCall.path does not match action template /files',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/drive/read': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/files\/.+$/.test(p),
        'apiCall.path does not match action template /files/{fileId}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/drive/download': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/files\/.+$/.test(p),
        'apiCall.path does not match action template /files/{fileId}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/drive/write': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/files$/.test(p),
        'apiCall.path does not match action template /files',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          name: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/drive/delete': {
    apiCallSchema: z.object({
      method: z.literal('DELETE'),
      path: safePath.refine(
        (p) => /^\/files\/.+$/.test(p),
        'apiCall.path does not match action template /files/{fileId}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/drive/update': {
    apiCallSchema: z.object({
      method: z.literal('PATCH'),
      path: safePath.refine(
        (p) => /^\/files\/.+$/.test(p),
        'apiCall.path does not match action template /files/{fileId}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/drive/copy': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/files\/[^/]+\/copy$/.test(p),
        'apiCall.path does not match action template /files/{fileId}/copy',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/drive/folder/create': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/files$/.test(p),
        'apiCall.path does not match action template /files',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          name: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/drive/search': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/files$/.test(p),
        'apiCall.path does not match action template /files',
      ),
      query: z
        .object({
          q: z.string(),
        })
        .catchall(z.string())
        .optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/drive/share': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/files\/[^/]+\/permissions$/.test(p),
        'apiCall.path does not match action template /files/{fileId}/permissions',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          type: z.enum(['user', 'group', 'domain', 'anyone']),
          role: z.enum(['reader', 'commenter', 'writer', 'owner']),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/drive/export': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/files\/[^/]+\/export$/.test(p),
        'apiCall.path does not match action template /files/{fileId}/export',
      ),
      query: z
        .object({
          mimeType: z.string(),
        })
        .catchall(z.string())
        .optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/drive/permission/list': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/files\/[^/]+\/permissions$/.test(p),
        'apiCall.path does not match action template /files/{fileId}/permissions',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/drive/permission/delete': {
    apiCallSchema: z.object({
      method: z.literal('DELETE'),
      path: safePath.refine(
        (p) => /^\/files\/[^/]+\/permissions\/.+$/.test(p),
        'apiCall.path does not match action template /files/{fileId}/permissions/{permissionId}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/drive/revision/list': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/files\/[^/]+\/revisions$/.test(p),
        'apiCall.path does not match action template /files/{fileId}/revisions',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/drive/quota/read': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/about$/.test(p),
        'apiCall.path does not match action template /about',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/drive/trash': {
    apiCallSchema: z.object({
      method: z.literal('PATCH'),
      path: safePath.refine(
        (p) => /^\/files\/.+$/.test(p),
        'apiCall.path does not match action template /files/{fileId}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          trashed: z.boolean(),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/drive/untrash': {
    apiCallSchema: z.object({
      method: z.literal('PATCH'),
      path: safePath.refine(
        (p) => /^\/files\/.+$/.test(p),
        'apiCall.path does not match action template /files/{fileId}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          trashed: z.boolean(),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/drive/change/list': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/changes$/.test(p),
        'apiCall.path does not match action template /changes',
      ),
      query: z
        .object({
          pageToken: z.string(),
        })
        .catchall(z.string())
        .optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/drive/revision/read': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/files\/[^/]+\/revisions\/.+$/.test(p),
        'apiCall.path does not match action template /files/{fileId}/revisions/{revisionId}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/drive/about/read': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/about$/.test(p),
        'apiCall.path does not match action template /about',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
};
