// AUTO-GENERATED by packages/schema-packs/scripts/generate-action-schemas.mts.
// DO NOT EDIT BY HAND. Regenerate with: pnpm -F @auto-nomos/schema-packs gen:schemas
// Source of truth: packages/adapters/spec/<pack>.yaml
//
// This file is the apiCall floor for the PDP proxy. Hand-curated overrides
// in <pack>/schemas.ts can tighten body shape further. See types.ts
// `mergeActionSchemas` for how the two layers combine.
// pack=google_contacts actions=9 mapped=9

import { z } from 'zod';
import type { ActionSchemas } from '../types.js';

const safePath = z
  .string()
  .min(1)
  .refine((p: string) => !p.includes('..') && !p.includes('//'), {
    message: 'apiCall.path must not contain ".." or "//" segments',
  });

export const generated: Partial<Record<string, ActionSchemas>> = {
  '/google/contacts/list': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/people\/me\/connections$/.test(p),
        'apiCall.path does not match action template /people/me/connections',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/contacts/search': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/people:searchContacts$/.test(p),
        'apiCall.path does not match action template /people:searchContacts',
      ),
      query: z
        .object({
          query: z.string(),
        })
        .catchall(z.string())
        .optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/contacts/read': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/.+$/.test(p),
        'apiCall.path does not match action template /{resourceName}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/contacts/create': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/people:createContact$/.test(p),
        'apiCall.path does not match action template /people:createContact',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/contacts/update': {
    apiCallSchema: z.object({
      method: z.literal('PATCH'),
      path: safePath.refine(
        (p) => /^\/[^/]+:updateContact$/.test(p),
        'apiCall.path does not match action template /{resourceName}:updateContact',
      ),
      query: z
        .object({
          updatePersonFields: z.string(),
        })
        .catchall(z.string())
        .optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/contacts/delete': {
    apiCallSchema: z.object({
      method: z.literal('DELETE'),
      path: safePath.refine(
        (p) => /^\/[^/]+:deleteContact$/.test(p),
        'apiCall.path does not match action template /{resourceName}:deleteContact',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/contacts/group/list': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/contactGroups$/.test(p),
        'apiCall.path does not match action template /contactGroups',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/contacts/group/read': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/.+$/.test(p),
        'apiCall.path does not match action template /{resourceName}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/contacts/batch_get': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/people:batchGet$/.test(p),
        'apiCall.path does not match action template /people:batchGet',
      ),
      query: z
        .object({
          resourceNames: z.string(),
        })
        .catchall(z.string())
        .optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
};
