// AUTO-GENERATED by packages/schema-packs/scripts/generate-action-schemas.mts.
// DO NOT EDIT BY HAND. Regenerate with: pnpm -F @auto-nomos/schema-packs gen:schemas
// Source of truth: packages/adapters/spec/<pack>.yaml
//
// This file is the apiCall floor for the PDP proxy. Hand-curated overrides
// in <pack>/schemas.ts can tighten body shape further. See types.ts
// `mergeActionSchemas` for how the two layers combine.
// pack=google_calendar actions=18 mapped=18

import { z } from 'zod';
import type { ActionSchemas } from '../types.js';

const safePath = z
  .string()
  .min(1)
  .refine((p: string) => !p.includes('..') && !p.includes('//'), {
    message: 'apiCall.path must not contain ".." or "//" segments',
  });

export const generated: Partial<Record<string, ActionSchemas>> = {
  '/google/calendar/event/list': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/calendars\/[^/]+\/events$/.test(p),
        'apiCall.path does not match action template /calendars/{calendarId}/events',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/calendar/event/read': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/calendars\/[^/]+\/events\/.+$/.test(p),
        'apiCall.path does not match action template /calendars/{calendarId}/events/{eventId}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/calendar/event/create': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/calendars\/[^/]+\/events$/.test(p),
        'apiCall.path does not match action template /calendars/{calendarId}/events',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          summary: z.string().min(1),
          start: z.record(z.string(), z.unknown()),
          end: z.record(z.string(), z.unknown()),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/calendar/event/update': {
    apiCallSchema: z.object({
      method: z.literal('PATCH'),
      path: safePath.refine(
        (p) => /^\/calendars\/[^/]+\/events\/.+$/.test(p),
        'apiCall.path does not match action template /calendars/{calendarId}/events/{eventId}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/calendar/event/delete': {
    apiCallSchema: z.object({
      method: z.literal('DELETE'),
      path: safePath.refine(
        (p) => /^\/calendars\/[^/]+\/events\/.+$/.test(p),
        'apiCall.path does not match action template /calendars/{calendarId}/events/{eventId}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/calendar/list/list': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/users\/me\/calendarList$/.test(p),
        'apiCall.path does not match action template /users/me/calendarList',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/calendar/list/read': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/calendars\/.+$/.test(p),
        'apiCall.path does not match action template /calendars/{calendarId}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/calendar/freebusy/read': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/freeBusy$/.test(p),
        'apiCall.path does not match action template /freeBusy',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          timeMin: z.string().min(1),
          timeMax: z.string().min(1),
          items: z.array(z.unknown()),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/calendar/event/quick_add': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/calendars\/[^/]+\/events\/quickAdd$/.test(p),
        'apiCall.path does not match action template /calendars/{calendarId}/events/quickAdd',
      ),
      query: z
        .object({
          text: z.string(),
        })
        .catchall(z.string())
        .optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/calendar/list/create': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/calendars$/.test(p),
        'apiCall.path does not match action template /calendars',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          summary: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/calendar/list/delete': {
    apiCallSchema: z.object({
      method: z.literal('DELETE'),
      path: safePath.refine(
        (p) => /^\/calendars\/.+$/.test(p),
        'apiCall.path does not match action template /calendars/{calendarId}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/calendar/event/move': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/calendars\/[^/]+\/events\/[^/]+\/move$/.test(p),
        'apiCall.path does not match action template /calendars/{calendarId}/events/{eventId}/move',
      ),
      query: z
        .object({
          destination: z.string(),
        })
        .catchall(z.string())
        .optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/calendar/event/import': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/calendars\/[^/]+\/events\/import$/.test(p),
        'apiCall.path does not match action template /calendars/{calendarId}/events/import',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          summary: z.string().min(1),
          start: z.record(z.string(), z.unknown()),
          end: z.record(z.string(), z.unknown()),
          iCalUID: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/calendar/meta/read': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/users\/me\/calendarList\/.+$/.test(p),
        'apiCall.path does not match action template /users/me/calendarList/{calendarId}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/calendar/acl/list': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/calendars\/[^/]+\/acl$/.test(p),
        'apiCall.path does not match action template /calendars/{calendarId}/acl',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/calendar/settings/read': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/users\/me\/settings$/.test(p),
        'apiCall.path does not match action template /users/me/settings',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/calendar/event/respond': {
    apiCallSchema: z.object({
      method: z.literal('PATCH'),
      path: safePath.refine(
        (p) => /^\/calendars\/[^/]+\/events\/.+$/.test(p),
        'apiCall.path does not match action template /calendars/{calendarId}/events/{eventId}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          attendees: z.array(z.unknown()),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/google/calendar/list/clear': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/calendars\/[^/]+\/clear$/.test(p),
        'apiCall.path does not match action template /calendars/{calendarId}/clear',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
};
