// AUTO-GENERATED by packages/schema-packs/scripts/generate-action-schemas.mts.
// DO NOT EDIT BY HAND. Regenerate with: pnpm -F @auto-nomos/schema-packs gen:schemas
// Source of truth: packages/adapters/spec/<pack>.yaml
//
// This file is the apiCall floor for the PDP proxy. Hand-curated overrides
// in <pack>/schemas.ts can tighten body shape further. See types.ts
// `mergeActionSchemas` for how the two layers combine.
// pack=linear actions=23 mapped=23

import { z } from 'zod';
import type { ActionSchemas } from '../types.js';

const safePath = z
  .string()
  .min(1)
  .refine((p: string) => !p.includes('..') && !p.includes('//'), {
    message: 'apiCall.path must not contain ".." or "//" segments',
  });

export const generated: Partial<Record<string, ActionSchemas>> = {
  '/linear/issue/list': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine((p) => /^\/$/.test(p), 'apiCall.path does not match action template /'),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          query: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/linear/issue/create': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine((p) => /^\/$/.test(p), 'apiCall.path does not match action template /'),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          query: z.string().min(1),
          variables: z.record(z.string(), z.unknown()),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/linear/issue/comment': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine((p) => /^\/$/.test(p), 'apiCall.path does not match action template /'),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          query: z.string().min(1),
          variables: z.record(z.string(), z.unknown()),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/linear/issue/read': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine((p) => /^\/$/.test(p), 'apiCall.path does not match action template /'),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          query: z.string().min(1),
          variables: z.record(z.string(), z.unknown()),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/linear/issue/update': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine((p) => /^\/$/.test(p), 'apiCall.path does not match action template /'),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          query: z.string().min(1),
          variables: z.record(z.string(), z.unknown()),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/linear/project/list': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine((p) => /^\/$/.test(p), 'apiCall.path does not match action template /'),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          query: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/linear/team/list': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine((p) => /^\/$/.test(p), 'apiCall.path does not match action template /'),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          query: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/linear/user/me': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine((p) => /^\/$/.test(p), 'apiCall.path does not match action template /'),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          query: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/linear/issue/delete': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine((p) => /^\/$/.test(p), 'apiCall.path does not match action template /'),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          query: z.string().min(1),
          variables: z.record(z.string(), z.unknown()),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/linear/issue/search': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine((p) => /^\/$/.test(p), 'apiCall.path does not match action template /'),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          query: z.string().min(1),
          variables: z.record(z.string(), z.unknown()),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/linear/workflow_state/list': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine((p) => /^\/$/.test(p), 'apiCall.path does not match action template /'),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          query: z.string().min(1),
          variables: z.record(z.string(), z.unknown()),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/linear/label/list': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine((p) => /^\/$/.test(p), 'apiCall.path does not match action template /'),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          query: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/linear/user/list': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine((p) => /^\/$/.test(p), 'apiCall.path does not match action template /'),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          query: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/linear/project/read': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine((p) => /^\/$/.test(p), 'apiCall.path does not match action template /'),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          query: z.string().min(1),
          variables: z.record(z.string(), z.unknown()),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/linear/project/create': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine((p) => /^\/$/.test(p), 'apiCall.path does not match action template /'),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          query: z.string().min(1),
          variables: z.record(z.string(), z.unknown()),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/linear/project/update': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine((p) => /^\/$/.test(p), 'apiCall.path does not match action template /'),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          query: z.string().min(1),
          variables: z.record(z.string(), z.unknown()),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/linear/comment/list': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine((p) => /^\/$/.test(p), 'apiCall.path does not match action template /'),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          query: z.string().min(1),
          variables: z.record(z.string(), z.unknown()),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/linear/issue/assign': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine((p) => /^\/$/.test(p), 'apiCall.path does not match action template /'),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          query: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/linear/project/archive': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine((p) => /^\/$/.test(p), 'apiCall.path does not match action template /'),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          query: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/linear/cycle/list': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine((p) => /^\/$/.test(p), 'apiCall.path does not match action template /'),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          query: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/linear/team/read': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine((p) => /^\/$/.test(p), 'apiCall.path does not match action template /'),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          query: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/linear/comment/create': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine((p) => /^\/$/.test(p), 'apiCall.path does not match action template /'),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          query: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/linear/issue/move': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine((p) => /^\/$/.test(p), 'apiCall.path does not match action template /'),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          query: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
};
