// AUTO-GENERATED by packages/schema-packs/scripts/generate-action-schemas.mts.
// DO NOT EDIT BY HAND. Regenerate with: pnpm -F @auto-nomos/schema-packs gen:schemas
// Source of truth: packages/adapters/spec/<pack>.yaml
//
// This file is the apiCall floor for the PDP proxy. Hand-curated overrides
// in <pack>/schemas.ts can tighten body shape further. See types.ts
// `mergeActionSchemas` for how the two layers combine.
// pack=notion actions=22 mapped=22

import { z } from 'zod';
import type { ActionSchemas } from '../types.js';

const safePath = z
  .string()
  .min(1)
  .refine((p: string) => !p.includes('..') && !p.includes('//'), {
    message: 'apiCall.path must not contain ".." or "//" segments',
  });

export const generated: Partial<Record<string, ActionSchemas>> = {
  '/notion/search': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/search$/.test(p),
        'apiCall.path does not match action template /search',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          query: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/notion/page/read': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/pages\/.+$/.test(p),
        'apiCall.path does not match action template /pages/{page_id}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/notion/block/read': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/blocks\/[^/]+\/children$/.test(p),
        'apiCall.path does not match action template /blocks/{block_id}/children',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/notion/block/append': {
    apiCallSchema: z.object({
      method: z.literal('PATCH'),
      path: safePath.refine(
        (p) => /^\/blocks\/[^/]+\/children$/.test(p),
        'apiCall.path does not match action template /blocks/{block_id}/children',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          children: z.array(z.unknown()),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/notion/page/create': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/pages$/.test(p),
        'apiCall.path does not match action template /pages',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          parent: z.record(z.string(), z.unknown()),
          properties: z.record(z.string(), z.unknown()),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/notion/database/query': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/databases\/[^/]+\/query$/.test(p),
        'apiCall.path does not match action template /databases/{database_id}/query',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/notion/page/update': {
    apiCallSchema: z.object({
      method: z.literal('PATCH'),
      path: safePath.refine(
        (p) => /^\/pages\/.+$/.test(p),
        'apiCall.path does not match action template /pages/{page_id}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/notion/database/read': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/databases\/.+$/.test(p),
        'apiCall.path does not match action template /databases/{database_id}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/notion/user/list': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/users$/.test(p),
        'apiCall.path does not match action template /users',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/notion/user/read': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/users\/.+$/.test(p),
        'apiCall.path does not match action template /users/{user_id}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/notion/block/delete': {
    apiCallSchema: z.object({
      method: z.literal('DELETE'),
      path: safePath.refine(
        (p) => /^\/blocks\/.+$/.test(p),
        'apiCall.path does not match action template /blocks/{block_id}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/notion/database/create': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/databases$/.test(p),
        'apiCall.path does not match action template /databases',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          parent: z.record(z.string(), z.unknown()),
          title: z.array(z.unknown()),
          properties: z.record(z.string(), z.unknown()),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/notion/database/update': {
    apiCallSchema: z.object({
      method: z.literal('PATCH'),
      path: safePath.refine(
        (p) => /^\/databases\/.+$/.test(p),
        'apiCall.path does not match action template /databases/{database_id}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/notion/block/retrieve': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/blocks\/.+$/.test(p),
        'apiCall.path does not match action template /blocks/{block_id}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/notion/block/update': {
    apiCallSchema: z.object({
      method: z.literal('PATCH'),
      path: safePath.refine(
        (p) => /^\/blocks\/.+$/.test(p),
        'apiCall.path does not match action template /blocks/{block_id}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/notion/comment/list': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/comments$/.test(p),
        'apiCall.path does not match action template /comments',
      ),
      query: z
        .object({
          block_id: z.string(),
        })
        .catchall(z.string())
        .optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/notion/comment/create': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/comments$/.test(p),
        'apiCall.path does not match action template /comments',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          parent: z.record(z.string(), z.unknown()),
          rich_text: z.array(z.unknown()),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/notion/user/me': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/users\/me$/.test(p),
        'apiCall.path does not match action template /users/me',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/notion/page/archive': {
    apiCallSchema: z.object({
      method: z.literal('PATCH'),
      path: safePath.refine(
        (p) => /^\/pages\/.+$/.test(p),
        'apiCall.path does not match action template /pages/{page_id}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          archived: z.boolean(),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/notion/page/search': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/search$/.test(p),
        'apiCall.path does not match action template /search',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          query: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/notion/page/restore': {
    apiCallSchema: z.object({
      method: z.literal('PATCH'),
      path: safePath.refine(
        (p) => /^\/pages\/.+$/.test(p),
        'apiCall.path does not match action template /pages/{page_id}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          archived: z.boolean(),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/notion/page/property/read': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/pages\/[^/]+\/properties\/.+$/.test(p),
        'apiCall.path does not match action template /pages/{page_id}/properties/{property_id}',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
};
