// AUTO-GENERATED by packages/schema-packs/scripts/generate-action-schemas.mts.
// DO NOT EDIT BY HAND. Regenerate with: pnpm -F @auto-nomos/schema-packs gen:schemas
// Source of truth: packages/adapters/spec/<pack>.yaml
//
// This file is the apiCall floor for the PDP proxy. Hand-curated overrides
// in <pack>/schemas.ts can tighten body shape further. See types.ts
// `mergeActionSchemas` for how the two layers combine.
// pack=slack actions=26 mapped=26

import { z } from 'zod';
import type { ActionSchemas } from '../types.js';

const safePath = z
  .string()
  .min(1)
  .refine((p: string) => !p.includes('..') && !p.includes('//'), {
    message: 'apiCall.path must not contain ".." or "//" segments',
  });

export const generated: Partial<Record<string, ActionSchemas>> = {
  '/slack/channel/list': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/conversations\.list$/.test(p),
        'apiCall.path does not match action template /conversations.list',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/slack/message/post': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/chat\.postMessage$/.test(p),
        'apiCall.path does not match action template /chat.postMessage',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          channel: z.string().min(1),
          text: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/slack/user/read': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/users\.info$/.test(p),
        'apiCall.path does not match action template /users.info',
      ),
      query: z
        .object({
          user: z.string(),
        })
        .catchall(z.string())
        .optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/slack/channel/history': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/conversations\.history$/.test(p),
        'apiCall.path does not match action template /conversations.history',
      ),
      query: z
        .object({
          channel: z.string(),
        })
        .catchall(z.string())
        .optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/slack/message/react': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/reactions\.add$/.test(p),
        'apiCall.path does not match action template /reactions.add',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          channel: z.string().min(1),
          name: z.string().min(1),
          timestamp: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/slack/user/list': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/users\.list$/.test(p),
        'apiCall.path does not match action template /users.list',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/slack/user/lookup': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/users\.lookupByEmail$/.test(p),
        'apiCall.path does not match action template /users.lookupByEmail',
      ),
      query: z
        .object({
          email: z.string(),
        })
        .catchall(z.string())
        .optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/slack/message/update': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/chat\.update$/.test(p),
        'apiCall.path does not match action template /chat.update',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          channel: z.string().min(1),
          ts: z.string().min(1),
          text: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/slack/message/delete': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/chat\.delete$/.test(p),
        'apiCall.path does not match action template /chat.delete',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          channel: z.string().min(1),
          ts: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/slack/message/reply': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/chat\.postMessage$/.test(p),
        'apiCall.path does not match action template /chat.postMessage',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          channel: z.string().min(1),
          thread_ts: z.string().min(1),
          text: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/slack/file/upload': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/files\.upload$/.test(p),
        'apiCall.path does not match action template /files.upload',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          channels: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/slack/dm/open': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/conversations\.open$/.test(p),
        'apiCall.path does not match action template /conversations.open',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          users: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/slack/channel/read': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/conversations\.info$/.test(p),
        'apiCall.path does not match action template /conversations.info',
      ),
      query: z
        .object({
          channel: z.string(),
        })
        .catchall(z.string())
        .optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/slack/message/search': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/search\.messages$/.test(p),
        'apiCall.path does not match action template /search.messages',
      ),
      query: z
        .object({
          query: z.string(),
        })
        .catchall(z.string())
        .optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/slack/channel/create': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/conversations\.create$/.test(p),
        'apiCall.path does not match action template /conversations.create',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          name: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/slack/channel/invite': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/conversations\.invite$/.test(p),
        'apiCall.path does not match action template /conversations.invite',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          channel: z.string().min(1),
          users: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/slack/message/pin': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/pins\.add$/.test(p),
        'apiCall.path does not match action template /pins.add',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          channel: z.string().min(1),
          timestamp: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/slack/message/schedule': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/chat\.scheduleMessage$/.test(p),
        'apiCall.path does not match action template /chat.scheduleMessage',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          channel: z.string().min(1),
          text: z.string().min(1),
          post_at: z.number().int(),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/slack/channel/topic': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/conversations\.setTopic$/.test(p),
        'apiCall.path does not match action template /conversations.setTopic',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          channel: z.string().min(1),
          topic: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/slack/message/unreact': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/reactions\.remove$/.test(p),
        'apiCall.path does not match action template /reactions.remove',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          channel: z.string().min(1),
          timestamp: z.string().min(1),
          name: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/slack/channel/archive': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/conversations\.archive$/.test(p),
        'apiCall.path does not match action template /conversations.archive',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          channel: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/slack/channel/unarchive': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/conversations\.unarchive$/.test(p),
        'apiCall.path does not match action template /conversations.unarchive',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          channel: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/slack/file/list': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/files\.list$/.test(p),
        'apiCall.path does not match action template /files.list',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/slack/file/delete': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/files\.delete$/.test(p),
        'apiCall.path does not match action template /files.delete',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          file: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/slack/file/read': {
    apiCallSchema: z.object({
      method: z.literal('GET'),
      path: safePath.refine(
        (p) => /^\/files\.info$/.test(p),
        'apiCall.path does not match action template /files.info',
      ),
      query: z
        .object({
          file: z.string(),
        })
        .catchall(z.string())
        .optional(),
      body: z.unknown().optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
  '/slack/channel/leave': {
    apiCallSchema: z.object({
      method: z.literal('POST'),
      path: safePath.refine(
        (p) => /^\/conversations\.leave$/.test(p),
        'apiCall.path does not match action template /conversations.leave',
      ),
      query: z.record(z.string(), z.string()).optional(),
      body: z
        .object({
          channel: z.string().min(1),
        })
        .passthrough()
        .optional(),
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },
};
