#!/usr/bin/env tsx
/**
 * Emits per-pack apiCallSchema bindings from packages/adapters/spec/*.yaml.
 *
 * Each generated file declares one schema per (pack, command) — locking the
 * HTTP method + path template + required body/query shape that the PDP
 * proxy will accept for that command. Hand-curated overrides in
 * <pack>/schemas.ts may tighten the body shape further; they win on merge.
 *
 * Run with: pnpm -F @auto-nomos/schema-packs gen:schemas
 *
 * Output is committed to the repo (no implicit codegen on build).
 */
import { loadAllAdapters, type Action, type Param } from '@auto-nomos/adapters';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = resolve(__dirname, '..');
const OUT_DIR = resolve(PKG_ROOT, 'src', '__generated__');

/**
 * Schema-pack id → adapter YAML id. `google` pack is the Drive umbrella
 * mapped to `google_drive.yaml`; everything else is 1:1. `filesystem` has
 * no HTTP adapter (local fs only) so it is intentionally absent.
 */
const PACK_TO_ADAPTER: Record<string, string> = {
  github: 'github',
  slack: 'slack',
  notion: 'notion',
  linear: 'linear',
  stripe: 'stripe',
  google: 'google_drive',
  google_calendar: 'google_calendar',
  google_gmail: 'google_gmail',
  google_docs: 'google_docs',
  google_sheets: 'google_sheets',
  google_tasks: 'google_tasks',
};

const HEADER = `// AUTO-GENERATED by packages/schema-packs/scripts/generate-action-schemas.mts.
// DO NOT EDIT BY HAND. Regenerate with: pnpm -F @auto-nomos/schema-packs gen:schemas
// Source of truth: packages/adapters/spec/<pack>.yaml
//
// This file is the apiCall floor for the PDP proxy. Hand-curated overrides
// in <pack>/schemas.ts can tighten body shape further. See types.ts
// \`mergeActionSchemas\` for how the two layers combine.
`;

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Turn an HTTP path template into a regex source string. Replaces each
 * `{var}` placeholder with `[^/]+` (single segment) — or `.+` when the
 * placeholder is the only content in the LAST segment, so paths like
 * `/contents/{path}` accept multi-segment file paths. Mixed segments
 * carrying both a placeholder and a literal suffix (Google's verb syntax
 * `{documentId}:batchUpdate`) keep the literal as a regex-escaped tail.
 * Pure-literal segments are regex-escaped. The regex is anchored.
 */
function pathTemplateToRegexSrc(tmpl: string): string {
  const segs = tmpl.split('/');
  const lastIdx = segs.length - 1;
  const placeholderOnly = /^\{[a-zA-Z_][a-zA-Z0-9_]*\}$/;
  const placeholderToken = /\{[a-zA-Z_][a-zA-Z0-9_]*\}/g;
  const out = segs.map((seg, i) => {
    if (seg === '') return seg;
    if (placeholderOnly.test(seg)) {
      return i === lastIdx ? '.+' : '[^/]+';
    }
    if (placeholderToken.test(seg)) {
      // Reset lastIndex from the .test() call above.
      placeholderToken.lastIndex = 0;
      let result = '';
      let lastIndex = 0;
      let match: RegExpExecArray | null;
      while ((match = placeholderToken.exec(seg)) !== null) {
        result += escapeRegex(seg.slice(lastIndex, match.index));
        result += '[^/]+';
        lastIndex = match.index + match[0].length;
      }
      result += escapeRegex(seg.slice(lastIndex));
      return result;
    }
    return escapeRegex(seg);
  });
  return '^' + out.join('/') + '$';
}

function paramTypeToZod(p: Param): string {
  if (p.enum && p.enum.length > 0) {
    const lits = p.enum.map((e) => JSON.stringify(e)).join(', ');
    return `z.enum([${lits}])`;
  }
  switch (p.type) {
    case 'string':
      return p.required ? 'z.string().min(1)' : 'z.string()';
    case 'integer':
      return 'z.number().int()';
    case 'number':
      return 'z.number()';
    case 'boolean':
      return 'z.boolean()';
    case 'array':
      return 'z.array(z.unknown())';
    case 'object':
      return 'z.record(z.string(), z.unknown())';
    default:
      return 'z.unknown()';
  }
}

function renderBodyShape(params: readonly Param[]): string | null {
  const bodyParams = params.filter((p) => (p.in === 'body' || p.in === 'form') && p.required);
  if (bodyParams.length === 0) return null;
  const fields = bodyParams.map((p) => `    ${JSON.stringify(p.name)}: ${paramTypeToZod(p)},`).join('\n');
  return `z.object({\n${fields}\n  }).passthrough()`;
}

function renderQueryShape(params: readonly Param[]): string | null {
  const required = params.filter((p) => p.in === 'query' && p.required);
  if (required.length === 0) return null;
  const fields = required
    .map((p) => `    ${JSON.stringify(p.name)}: z.string(),`)
    .join('\n');
  return `z.object({\n${fields}\n  }).catchall(z.string())`;
}

function renderAction(command: string, action: Action): string {
  const pathRe = pathTemplateToRegexSrc(action.http.path);
  const body = renderBodyShape(action.params);
  const query = renderQueryShape(action.params);
  const bodyLine = body
    ? `      body: ${body.replace(/\n/g, '\n      ')}.optional(),`
    : '      body: z.unknown().optional(),';
  const queryLine = query
    ? `      query: ${query.replace(/\n/g, '\n      ')}.optional(),`
    : '      query: z.record(z.string(), z.string()).optional(),';
  // Emit `new RegExp(...)` rather than a literal so forward slashes in the
  // path template don't have to be escaped.
  const reLiteral = `new RegExp(${JSON.stringify(pathRe)})`;
  const tmplLiteral = JSON.stringify(`apiCall.path does not match action template ${action.http.path}`);
  return `  ${JSON.stringify(command)}: {
    apiCallSchema: z.object({
      method: z.literal(${JSON.stringify(action.http.method)}),
      path: safePath.refine((p) => ${reLiteral}.test(p), ${tmplLiteral}),
${queryLine}
${bodyLine}
      headers: z.record(z.string(), z.string()).optional(),
    }),
  },`;
}

function renderPack(packId: string, actions: readonly Action[], actionToCommand: Record<string, string>): string {
  const lines: string[] = [];
  let skipped = 0;
  for (const action of actions) {
    const command = actionToCommand[action.id];
    if (!command) {
      skipped++;
      continue;
    }
    lines.push(renderAction(command, action));
  }
  const meta = `pack=${packId} actions=${actions.length} mapped=${lines.length}${skipped ? ` skipped=${skipped}` : ''}`;
  return `${HEADER}// ${meta}

import { z } from 'zod';
import type { ActionSchemas } from '../types.js';

const safePath = z
  .string()
  .min(1)
  .refine((p: string) => !p.includes('..') && !p.includes('//'), {
    message: 'apiCall.path must not contain ".." or "//" segments',
  });

export const generated: Partial<Record<string, ActionSchemas>> = {
${lines.join('\n')}
};
`;
}

async function loadActionToCommand(packId: string): Promise<Record<string, string>> {
  const mod = await import(resolve(PKG_ROOT, 'src', packId, 'actions.ts'));
  if (typeof mod.actionToCommand !== 'object' || mod.actionToCommand == null) {
    throw new Error(`pack ${packId} does not export actionToCommand`);
  }
  return mod.actionToCommand as Record<string, string>;
}

async function main(): Promise<void> {
  const adapters = loadAllAdapters();
  mkdirSync(OUT_DIR, { recursive: true });
  for (const [packId, adapterId] of Object.entries(PACK_TO_ADAPTER)) {
    const adapter = adapters.get(adapterId);
    if (!adapter) {
      throw new Error(`adapter spec ${adapterId} not found for pack ${packId}`);
    }
    const actionToCommand = await loadActionToCommand(packId);
    // Cross-check: every actionToCommand key must exist in the YAML.
    const yamlIds = new Set(adapter.actions.map((a) => a.id));
    for (const id of Object.keys(actionToCommand)) {
      if (!yamlIds.has(id)) {
        throw new Error(`pack ${packId}: actionToCommand has \`${id}\` but ${adapterId}.yaml does not`);
      }
    }
    const code = renderPack(packId, adapter.actions, actionToCommand);
    const outPath = resolve(OUT_DIR, `${packId}-api-schemas.ts`);
    writeFileSync(outPath, code, 'utf8');
    const mapped = adapter.actions.filter((a) => actionToCommand[a.id]).length;
    console.log(
      `generated ${packId}-api-schemas.ts — ${mapped}/${adapter.actions.length} actions bound`,
    );
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
